  export const products = [
    {
      name: "حقيبة ريزيه",
      shortDescription: "حقيبة يد أنيقة بنقشة الفهد ولمسات جلدية بنية، مزودة بسلسلة ذهبية تضيف لمسة فاخرة.",
      image: "/images/1/Kaki.jpg",
      hoverImage: "/images/1/Coffee.jpg",
      price: 20,
      id: "1",
      slug: "Rize",
      images: [
        "/images/1/Coffee.jpg",
        "/images/1/Brown.jpg",
        "/images/1/Kaki.jpg",
        "/images/1/(1).jpg",
        "/images/1/(2).jpg",
        "/images/1/(3).jpg",
        "/images/1/(4).jpg",
        "/images/1/(5).jpg",
      ],
      colors: [
        { name: "قهوة", hex: "#6F4E37" },
        { name: "بني", hex: "#964B00" },
        { name: "رملي", hex: "#b0998b" }
      ],
    },
    {
      name: "حقيبة الامواج",
      shortDescription: "حقيبة يد جلدية أنيقة ، بتصميم مموّج يدوي ومقبض علوي مجعد، مزودة بسلسلة ذهبية ووسم فاخر.",
      image: "/images/2/Kaki.jpg",
      hoverImage: "/images/2/White.jpg",
      price: 17,
      id: "2",
      slug: "Wavea",
      images: [
        "/images/2/Black.jpg",
        "/images/2/Kaki.jpg",
        "/images/2/White.jpg",
        "/images/2/Phosphorescent.jpg",
        "/images/2/(1).jpg",
        "/images/2/(2).jpg",
        "/images/2/(3).jpg",
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "اسود", hex: "#000000" },
        { name: "رملي", hex: "#b0998b" },
        { name: "فستقي", hex: "#90EE90" }
      ],
    },
    {
      name: "حقيبة القش",
      shortDescription: "حقيبة كروس أنيقة مصنوعة من القش الطبيعي مع غطاء جلدي ، بتفاصيل مضفّرة ولمسة عصرية من الشرّابات والحبل القطني.",
      image: "/images/4/Black.jpg",
      hoverImage: "/images/4/White.jpg",
      price: 22,
      id: "3",
      slug: "straw",
      images: [
        "/images/4/Black.jpg",
        "/images/4/Brown.jpg",
        "/images/4/White.jpg",
        "/images/4/Yellow.jpg",
        "/images/4/1.jpg",
        "/images/4/2.jpg",
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "اسود", hex: "#000000" },
        { name: "كستنائي", hex: "#964B00" },
        { name: "ليموني", hex: "#FFFF00" }
      ],
    },
    {
      name: "حقيبة الصدفة",
      shortDescription: "حقيبة جلدية عريقة , مصنوعة بالكامل من الجلد مع بعض اللمسات الذهبية التي تعطي طابع فخم",
      image: "/images/5/Black.jpg",
      hoverImage: "/images/5/Brawn.jpg",
      price: 23,
      salePrice: 21,
      id: "4",
      slug: "Shell",
      images: [
        "/images/5/Black.jpg",
        "/images/5/Brawn.jpg",
        "/images/5/1.jpg",
        "/images/5/2.jpg"
      ],
      colors: [
        { name: "كستنائي", hex: "#964B00" },
        { name: "اسود", hex: "#000000" },
      ],
    },
    {
      name: "حقيبة الالماس",
      shortDescription: "حقيبة الألماس المميزة , ذات طابع الماسي يحتوي الوان الطيف السبع , وتحتوي على سلسلة تعطي طابع كلاسيكي",
      image: "/images/6/Rainbow.jpg",
      hoverImage: "/images/6/White.jpg",
      price: 20,
      salePrice: 18,
      id: "5",
      slug: "Diamond",
      images: [
        "/images/6/Rainbow.jpg",
        "/images/6/White.jpg",
        "/images/6/1.jpg",
        "/images/6/2.jpg",
        "/images/6/3.jpg"
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "ملون", hex: "#DDA0DD" },
      ],
    },
    {
      name: "حقيبة القطة الذهبية",
      shortDescription: "حقيبة القطة الذهبية بتصميم عصري بسيط , تحتوي على حزام مزخرف , وتفاصيل ذهبية تعطي طابع فخم",
      image: "/images/7/Black.jpg",
      hoverImage: "/images/7/Pink.jpg",
      price: 18,
      salePrice: 16,
      id: "6",
      slug: "Cat",
      images: [
        "/images/7/Black.jpg",
        "/images/7/Pink.jpg",
        "/images/7/1.jpg",
        "/images/7/2.jpg",
        "/images/7/3.jpg",
        "/images/7/4.jpg",
        "/images/7/Blue.jpg",
        "/images/7/Kaki&Pink.jpg",
        "/images/7/Green.jpg",
        "/images/7/Yellow.jpg",
      ],
      colors: [
        { name: "رملي", hex: "#b0998b" },
        { name: "اسود", hex: "#000000" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "فستقي", hex: "#008000" },
        { name: "وردي", hex: "#FFC0CB" },
        { name: "ليموني", hex: "#FFFF00" },
      ],
    },
    {
      name: "حقيبة دلو القماش",
      shortDescription: "حقيبة القماش المقلم , قماش مخطط ذات ملمس خشن , بتصميم راقي , مع لمسات ذهبية تعطي طابع الفخامة",
      image: "/images/5/Black.jpg",
      hoverImage: "/images/5/Brawn.jpg",
      price: 18,
      id: "7",
      slug: "Canvas",
      images: [
        "/images/9/Black.jpg",
        "/images/9/Braown.jpg",
        "/images/9/Blue.jpg",
        "/images/9/Red.jpg"
      ],
      colors: [
        { name: "كستنائي", hex: "#964B00" },
        { name: "اسود", hex: "#000000" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "عنابي", hex: "#FF0000" },
      ],
    },
    {
      name: "الحقيبة الملكية",
      shortDescription: "حقيبة جلدية , تحتوي نقشة ملكية مع لمسات ذهبية تعطي طابع فخم و راقي",
      image: "/images/10/Blue.jpg",
      hoverImage: "/images/10/Pink.jpg",
      price: 17,
      id: "8",
      slug: "Royal",
      images: [
        "/images/10/Black.jpg",
        "/images/10/Brown.jpg",
        "/images/10/Blue.jpg",
        "/images/10/Khaki.jpg",
        "/images/10/Pink.jpg"
      ],
      colors: [
        { name: "كستنائي", hex: "#b0998b" },
        { name: "اسود", hex: "#000000" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "وردي", hex: "#FFC0CB" },
        { name: "بني", hex: "#964B00" },
      ],
    },
    {
      name: "حقيبة اللؤلؤ",
      shortDescription: "حقيبة اللؤلؤ المميزة , تحتوي على مقبض من اللؤلؤ وسلسلة فضية تعطي طابع كلاسيكي",
      image: "/images/11/Pink.jpg",
      hoverImage: "/images/11/Silver.jpg",
      price: 17,
      id: "9",
      slug: "Pearl",
      images: [
        "/images/11/Lemon.jpg",
        "/images/11/White.jpg",
        "/images/11/Blue.jpg",
        "/images/11/Silver.jpg",
        "/images/11/Pink.jpg"
      ],
      colors: [
        { name: "ليموني", hex: "#FFFF00" },
        { name: "ابيض", hex: "#ffffff" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "وردي", hex: "#FFC0CB" },
        { name: "فضي لامع", hex: "#C0C0C0" },
      ],
    },
    {
      name: "حقيبة القمر",
      shortDescription: "حقيبة القمر الجلدية , تاتي بحزام جلدي فخم وحزام قماشي عريض مع بعض التفاصيل الذهبية",
      image: "/images/12/white.jpg",
      hoverImage: "/images/12/wheat.jpg",
      price: 17,
      id: "10",
      slug: "Moon",
      images: [
        "/images/12/1.jpg",
        "/images/12/2.jpg",
        "/images/12/3.jpg",
        "/images/12/Black.jpg",
        "/images/12/Blue.jpg",
        "/images/12/Brown.jpg",
        "/images/12/Kaki.jpg",
        "/images/12/wheat.jpg",
        "/images/12/white.jpg"
      ],
      colors: [
        { name: "سكري", hex: "#f5deb3" },
        { name: "رملي", hex: "#b0998b" },
        { name: "ابيض", hex: "#ffffff" },
        { name: "بني", hex: "#964B00" },
        { name: "اسود", hex: "#000000" },
      ],
    },
    {
      name: "حقيبة خطوط القماش",
      shortDescription: "حقيبة القماش  , قماش مخطط ذات ملمس خشن , بتصميم راقي , مع لمسات ذهبية تعطي طابع",
      image: "/images/13/blue.jpg",
      hoverImage: "/images/13/yellow.jpg",
      price: 18,
      id: "11",
      slug: "Fabric",
      images: [
        "/images/13/1.jpg",
        "/images/13/2.jpg",
        "/images/13/3.jpg",
        "/images/13/black.jpg",
        "/images/13/blue.jpg",
        "/images/13/brown.jpg",
        "/images/13/gray.jpg",
        "/images/13/red.jpg",
        "/images/13/yellow.jpg"
      ],
      colors: [
        { name: "ابيض احمر", hex: "#FF0000" },
        { name: "ابيض ازرق", hex: "#0000FF" },
        { name: "ابيض اسود", hex: "#000000" },
        { name: "ابيض اصفر", hex: "#FFFF00" },
        { name: "ابيض بني", hex: "#964B00" },
        { name: "اسود رمادي", hex: "#C0C0C0" },
      ],
    },
    {
      name: "حقيبة القلب",
      shortDescription: "حقيبة يد أنيقة بتصميم عصري، مزودة بحزام مطرز وزينة قلبية لامعة.",
      image: "/images/14/pink.jpg",
      hoverImage: "/images/14/blue.jpg",
      price: 17,
      salePrice: 15,
      id: "12",
      slug: "Heart",
      images: [
        "/images/14/black.jpg",
        "/images/14/blue.jpg",
        "/images/14/red.jpg",
        "/images/14/white.jpg",
        "/images/14/pink.jpg",
        "/images/14/green.jpg"
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "اسود", hex: "#000000" },
        { name: "عنابي", hex: "#FF0000" },
        { name: "فستقي", hex: "#008000" },
        { name: "وردي", hex: "#FFC0CB" },
      ],
    },
  ];
