  export const products = [
    {
      name: "حقيبة ريزيه",
      shortDescription: "حقيبة يد أنيقة بنقشة الفهد ولمسات جلدية بنية، مزودة بسلسلة ذهبية تضيف لمسة فاخرة.",
      image: "/images/1/Kaki.webp",
      hoverImage: "/images/1/Coffee.webp",
      price: 20,
      id: "1",
      slug: "Rize",
      images: [
        "/images/1/Coffee.webp",
        "/images/1/Brown.webp",
        "/images/1/Kaki.webp",
        "/images/1/(1).webp",
        "/images/1/(2).webp",
        "/images/1/(3).webp",
        "/images/1/(4).webp",
        "/images/1/(5).webp",
      ],
      colors: [
        { name: "قهوة", hex: "#6F4E37" },
        { name: "بني", hex: "#964B00" },
        { name: "رملي", hex: "#b0998b" }
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة الامواج",
      shortDescription: "حقيبة يد جلدية أنيقة ، بتصميم مموّج يدوي ومقبض علوي مجعد، مزودة بسلسلة ذهبية ووسم فاخر.",
      image: "/images/2/Kaki.webp",
      hoverImage: "/images/2/White.webp",
      price: 17,
      id: "2",
      slug: "Wavea",
      images: [
        "/images/2/Black.webp",
        "/images/2/Kaki.webp",
        "/images/2/White.webp",
        "/images/2/Phosphorescent.webp",
        "/images/2/(1).webp",
        "/images/2/(2).webp",
        "/images/2/(3).webp",
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "اسود", hex: "#000000" },
        { name: "رملي", hex: "#b0998b" },
        { name: "فستقي", hex: "#90EE90" }
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة القش",
      shortDescription: "حقيبة كروس أنيقة مصنوعة من القش الطبيعي مع غطاء جلدي ، بتفاصيل مضفّرة ولمسة عصرية من الشرّابات والحبل القطني.",
      image: "/images/4/Black.webp",
      hoverImage: "/images/4/White.webp",
      price: 22,
      id: "3",
      slug: "straw",
      images: [
        "/images/4/Black.webp",
        "/images/4/Brown.webp",
        "/images/4/White.webp",
        "/images/4/Yellow.webp",
        "/images/4/1.webp",
        "/images/4/2.webp",
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "اسود", hex: "#000000" },
        { name: "كستنائي", hex: "#964B00" },
        { name: "ليموني", hex: "#FFFF00" }
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة الصدفة",
      shortDescription: "حقيبة جلدية عريقة , مصنوعة بالكامل من الجلد مع بعض اللمسات الذهبية التي تعطي طابع فخم",
      image: "/images/5/Black.webp",
      hoverImage: "/images/5/Brawn.webp",
      price: 21,
      id: "4",
      slug: "Shell",
      images: [
        "/images/5/Black.webp",
        "/images/5/Brawn.webp",
        "/images/5/1.webp",
        "/images/5/2.webp"
      ],
      colors: [
        { name: "كستنائي", hex: "#964B00" },
        { name: "اسود", hex: "#000000" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة الالماس",
      shortDescription: "حقيبة الألماس المميزة , ذات طابع الماسي يحتوي الوان الطيف السبع , وتحتوي على سلسلة تعطي طابع كلاسيكي",
      image: "/images/6/Rainbow.webp",
      hoverImage: "/images/6/White.webp",
      price: 18,
      id: "5",
      slug: "Diamond",
      images: [
        "/images/6/Rainbow.webp",
        "/images/6/White.webp",
        "/images/6/1.webp",
        "/images/6/2.webp",
        "/images/6/3.webp"
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "ملون", hex: "#DDA0DD" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة القطة الذهبية",
      shortDescription: "حقيبة القطة الذهبية بتصميم عصري بسيط , تحتوي على حزام مزخرف , وتفاصيل ذهبية تعطي طابع فخم",
      image: "/images/7/Black.webp",
      hoverImage: "/images/7/Pink.webp",
      price: 16,
      id: "6",
      slug: "Cat",
      images: [
        "/images/7/Black.webp",
        "/images/7/Pink.webp",
        "/images/7/1.webp",
        "/images/7/2.webp",
        "/images/7/3.webp",
        "/images/7/4.webp",
        "/images/7/Blue.webp",
        "/images/7/Kaki&Pink.webp",
        "/images/7/Green.webp",
        "/images/7/Yellow.webp",
      ],
      colors: [
        { name: "رملي", hex: "#b0998b" },
        { name: "اسود", hex: "#000000" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "فستقي", hex: "#008000" },
        { name: "وردي", hex: "#FFC0CB" },
        { name: "ليموني", hex: "#FFFF00" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة دلو القماش",
      shortDescription: "حقيبة القماش المقلم , قماش مخطط ذات ملمس خشن , بتصميم راقي , مع لمسات ذهبية تعطي طابع الفخامة",
      image: "/images/9/Black.webp",
      hoverImage: "/images/5/Brawn.webp",
      price: 18,
      id: "7",
      slug: "Canvas",
      images: [
        "/images/9/Black.webp",
        "/images/9/Braown.webp",
        "/images/9/Blue.webp",
        "/images/9/Red.webp"
      ],
      colors: [
        { name: "كستنائي", hex: "#964B00" },
        { name: "اسود", hex: "#000000" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "عنابي", hex: "#FF0000" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "الحقيبة الملكية",
      shortDescription: "حقيبة جلدية , تحتوي نقشة ملكية مع لمسات ذهبية تعطي طابع فخم و راقي",
      image: "/images/10/Blue.webp",
      hoverImage: "/images/10/Pink.webp",
      price: 17,
      id: "8",
      slug: "Royal",
      images: [
        "/images/10/Black.webp",
        "/images/10/Brown.webp",
        "/images/10/Blue.webp",
        "/images/10/Khaki.webp",
        "/images/10/Pink.webp"
      ],
      colors: [
        { name: "كستنائي", hex: "#b0998b" },
        { name: "اسود", hex: "#000000" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "وردي", hex: "#FFC0CB" },
        { name: "بني", hex: "#964B00" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة اللؤلؤ",
      shortDescription: "حقيبة اللؤلؤ المميزة , تحتوي على مقبض من اللؤلؤ وسلسلة فضية تعطي طابع كلاسيكي",
      image: "/images/11/Pink.webp",
      hoverImage: "/images/11/Silver.webp",
      price: 17,
      id: "9",
      slug: "Pearl",
      images: [
        "/images/11/Lemon.webp",
        "/images/11/White.webp",
        "/images/11/Blue.webp",
        "/images/11/Silver.webp",
        "/images/11/Pink.webp"
      ],
      colors: [
        { name: "ليموني", hex: "#FFFF00" },
        { name: "ابيض", hex: "#ffffff" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "وردي", hex: "#FFC0CB" },
        { name: "فضي لامع", hex: "#C0C0C0" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة القمر",
      shortDescription: "حقيبة القمر الجلدية , تاتي بحزام جلدي فخم وحزام قماشي عريض مع بعض التفاصيل الذهبية",
      image: "/images/12/white.webp",
      hoverImage: "/images/12/wheat.webp",
      price: 17,
      id: "10",
      slug: "Moon",
      images: [
        "/images/12/1.webp",
        "/images/12/2.webp",
        "/images/12/3.webp",
        "/images/12/Black.webp",
        "/images/12/Blue.webp",
        "/images/12/Brown.webp",
        "/images/12/Kaki.webp",
        "/images/12/wheat.webp",
        "/images/12/white.webp"
      ],
      colors: [
        { name: "سكري", hex: "#f5deb3" },
        { name: "رملي", hex: "#b0998b" },
        { name: "ابيض", hex: "#ffffff" },
        { name: "بني", hex: "#964B00" },
        { name: "اسود", hex: "#000000" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة خطوط القماش",
      shortDescription: "حقيبة القماش  , قماش مخطط ذات ملمس خشن , بتصميم راقي , مع لمسات ذهبية تعطي طابع",
      image: "/images/13/blue.webp",
      hoverImage: "/images/13/yellow.webp",
      price: 18,
      id: "11",
      slug: "Fabric",
      images: [
        "/images/13/1.webp",
        "/images/13/2.webp",
        "/images/13/3.webp",
        "/images/13/black.webp",
        "/images/13/blue.webpg",
        "/images/13/brown.webp",
        "/images/13/gray.webp",
        "/images/13/red.webp",
        "/images/13/yellow.webp"
      ],
      colors: [
        { name: "ابيض احمر", hex: "#FF0000" },
        { name: "ابيض ازرق", hex: "#0000FF" },
        { name: "ابيض اسود", hex: "#000000" },
        { name: "ابيض اصفر", hex: "#FFFF00" },
        { name: "ابيض بني", hex: "#964B00" },
        { name: "اسود رمادي", hex: "#C0C0C0" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
    {
      name: "حقيبة القلب",
      shortDescription: "حقيبة يد أنيقة بتصميم عصري، مزودة بحزام مطرز وزينة قلبية لامعة.",
      image: "/images/14/pink.webp",
      hoverImage: "/images/14/blue.webp",
      price: 15,
      id: "12",
      slug: "Heart",
      images: [
        "/images/14/black.webp",
        "/images/14/blue.webp",
        "/images/14/red.webp",
        "/images/14/white.webp",
        "/images/14/pink.webp",
        "/images/14/green.webp"
      ],
      colors: [
        { name: "ابيض", hex: "#ffffff" },
        { name: "ازرق ملكي", hex: "#0000FF" },
        { name: "اسود", hex: "#000000" },
        { name: "عنابي", hex: "#FF0000" },
        { name: "فستقي", hex: "#008000" },
        { name: "وردي", hex: "#FFC0CB" },
      ],
      info: {
    material: "جلد صناعي عالي الجودة",
    strap: "حزام مزخرف قابل للفصل",
    interior: "جيب داخلي بسحاب لتخزين الأغراض الصغيرة",
  },
    },
  ];
